# Generated by Django 5.2.3 on 2025-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
