# Generated by Django 5.2.3 on 2025-07-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prescricao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='CID11',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
